/* Fantasy Atlas audio manifest — generated; see audio/CREDITS.md.
 * All files CC0 / public domain (or original synthesis). Paths are relative to maps/index.html.
 * Loudness: sfx ≈ -14 LUFS (short clips peak-normalised, peaks ≤ -1 dBTP), amb ≈ -20 LUFS mono seamless loops,
 * bgm ≈ -16 LUFS stereo seamless loops (loop point crossfaded, so play with loop=true from 0). */
window.AUDIO = {
  sfx: {
    jump: ["audio/sfx/jump_1.mp3", "audio/sfx/jump_2.mp3"],
    djump: ["audio/sfx/djump_1.mp3", "audio/sfx/djump_2.mp3"],
    land: ["audio/sfx/land_1.mp3", "audio/sfx/land_2.mp3", "audio/sfx/land_3.mp3"],
    step_grass: ["audio/sfx/step_grass_1.mp3", "audio/sfx/step_grass_2.mp3", "audio/sfx/step_grass_3.mp3", "audio/sfx/step_grass_4.mp3", "audio/sfx/step_grass_5.mp3"],
    step_stone: ["audio/sfx/step_stone_1.mp3", "audio/sfx/step_stone_2.mp3", "audio/sfx/step_stone_3.mp3", "audio/sfx/step_stone_4.mp3"],
    step_wood: ["audio/sfx/step_wood_1.mp3", "audio/sfx/step_wood_2.mp3", "audio/sfx/step_wood_3.mp3", "audio/sfx/step_wood_4.mp3"],
    step_snow: ["audio/sfx/step_snow_1.mp3", "audio/sfx/step_snow_2.mp3", "audio/sfx/step_snow_3.mp3", "audio/sfx/step_snow_4.mp3"],
    splash: ["audio/sfx/splash_1.mp3", "audio/sfx/splash_2.mp3", "audio/sfx/splash_3.mp3"],
    swim: ["audio/sfx/swim_1.mp3", "audio/sfx/swim_2.mp3", "audio/sfx/swim_3.mp3"],
    door_wood: ["audio/sfx/door_wood_1.mp3", "audio/sfx/door_wood_2.mp3", "audio/sfx/door_wood_3.mp3"],
    door_metal: ["audio/sfx/door_metal_1.mp3", "audio/sfx/door_metal_2.mp3"],
    door_stone: ["audio/sfx/door_stone_1.mp3", "audio/sfx/door_stone_2.mp3"],
    gate_chain: ["audio/sfx/gate_chain_1.mp3", "audio/sfx/gate_chain_2.mp3"],
    lever: ["audio/sfx/lever_1.mp3", "audio/sfx/lever_2.mp3"],
    bell: ["audio/sfx/bell_1.mp3", "audio/sfx/bell_2.mp3", "audio/sfx/bell_3.mp3"],
    chest: ["audio/sfx/chest_1.mp3", "audio/sfx/chest_2.mp3"],
    fire: ["audio/sfx/fire_1.mp3", "audio/sfx/fire_2.mp3", "audio/sfx/fire_3.mp3"],
    explosion: ["audio/sfx/explosion_1.mp3", "audio/sfx/explosion_2.mp3", "audio/sfx/explosion_3.mp3"],
    thunder: ["audio/sfx/thunder_1.mp3", "audio/sfx/thunder_2.mp3"],
    magic: ["audio/sfx/magic_1.mp3", "audio/sfx/magic_2.mp3", "audio/sfx/magic_3.mp3", "audio/sfx/magic_4.mp3", "audio/sfx/magic_5.mp3"],
    sparkle: ["audio/sfx/sparkle_1.mp3", "audio/sfx/sparkle_2.mp3", "audio/sfx/sparkle_3.mp3"],
    water_pour: ["audio/sfx/water_pour_1.mp3", "audio/sfx/water_pour_2.mp3"],
    bubble: ["audio/sfx/bubble_1.mp3", "audio/sfx/bubble_2.mp3", "audio/sfx/bubble_3.mp3"],
    wind_gust: ["audio/sfx/wind_gust_1.mp3", "audio/sfx/wind_gust_2.mp3"],
    creak: ["audio/sfx/creak_1.mp3", "audio/sfx/creak_2.mp3", "audio/sfx/creak_3.mp3"],
    metal_hit: ["audio/sfx/metal_hit_1.mp3", "audio/sfx/metal_hit_2.mp3", "audio/sfx/metal_hit_3.mp3"],
    anvil: ["audio/sfx/anvil_1.mp3", "audio/sfx/anvil_2.mp3"],
    coins: ["audio/sfx/coins_1.mp3", "audio/sfx/coins_2.mp3", "audio/sfx/coins_3.mp3"],
    book: ["audio/sfx/book_1.mp3", "audio/sfx/book_2.mp3", "audio/sfx/book_3.mp3"],
    glass: ["audio/sfx/glass_1.mp3", "audio/sfx/glass_2.mp3", "audio/sfx/glass_3.mp3"],
    bird_flap: ["audio/sfx/bird_flap_1.mp3", "audio/sfx/bird_flap_2.mp3"],
    crow: ["audio/sfx/crow_1.mp3", "audio/sfx/crow_2.mp3"],
    engine: ["audio/sfx/engine_1.mp3", "audio/sfx/engine_2.mp3"],
    horn: ["audio/sfx/horn_1.mp3", "audio/sfx/horn_2.mp3"],
    alarm: ["audio/sfx/alarm_1.mp3", "audio/sfx/alarm_2.mp3"],
    gunshot_distant: ["audio/sfx/gunshot_distant_1.mp3", "audio/sfx/gunshot_distant_2.mp3", "audio/sfx/gunshot_distant_3.mp3"],
    ui_click: ["audio/sfx/ui_click_1.mp3", "audio/sfx/ui_click_2.mp3"],
    ui_open: ["audio/sfx/ui_open_1.mp3", "audio/sfx/ui_open_2.mp3"],
    discover: ["audio/sfx/discover_1.mp3", "audio/sfx/discover_2.mp3"],
    travel: ["audio/sfx/travel_1.mp3", "audio/sfx/travel_2.mp3"],
    interact: ["audio/sfx/interact_1.mp3", "audio/sfx/interact_2.mp3"],
  },
  amb: {
    forest: "audio/amb/forest.mp3",
    swamp: "audio/amb/swamp.mp3",
    cave: "audio/amb/cave.mp3",
    crypt: "audio/amb/crypt.mp3",
    town: "audio/amb/town.mp3",
    market: "audio/amb/market.mp3",
    harbor: "audio/amb/harbor.mp3",
    river: "audio/amb/river.mp3",
    snow_wind: "audio/amb/snow_wind.mp3",
    mountain_wind: "audio/amb/mountain_wind.mp3",
    lava: "audio/amb/lava.mp3",
    castle: "audio/amb/castle.mp3",
    magic_hum: "audio/amb/magic_hum.mp3",
    night_insects: "audio/amb/night_insects.mp3",
    storm: "audio/amb/storm.mp3",
    city_ruin: "audio/amb/city_ruin.mp3",
    mall_indoor: "audio/amb/mall_indoor.mp3",
    ship_ice: "audio/amb/ship_ice.mp3",
    field_birds: "audio/amb/field_birds.mp3",
  },
  bgm: {
    dungeon: "audio/bgm/dungeon.mp3",
    village: "audio/bgm/village.mp3",
    kingdom: "audio/bgm/kingdom.mp3",
    magic: "audio/bgm/magic.mp3",
    lands: "audio/bgm/lands.mp3",
    lands_boss: "audio/bgm/lands_boss.mp3",
    orario: "audio/bgm/orario.mp3",
    tarkov: "audio/bgm/tarkov.mp3",
    tarkov_tension: "audio/bgm/tarkov_tension.mp3",
  },
  credits: [
    {"file": "audio/sfx/fire_3.mp3", "title": "Fire Crackling", "author": "AntumDeluge", "license": "CC0 1.0", "url": "https://opengameart.org/content/fire-crackling"},
    {"file": "audio/sfx/bird_flap_1.mp3", "title": "Large Wings Flap", "author": "AntumDeluge", "license": "CC0 1.0", "url": "https://opengameart.org/content/large-wings-flap"},
    {"file": "audio/sfx/alarm_2.mp3", "title": "Sirens and Alarm Noise", "author": "aquinn", "license": "CC0 1.0", "url": "https://opengameart.org/content/sirens-and-alarm-noise"},
    {"file": "audio/sfx/gate_chain_1.mp3", "title": "Chain winch sounds", "author": "bart", "license": "CC0 1.0", "url": "https://opengameart.org/content/chain-winch-sounds"},
    {"file": "audio/sfx/door_stone_1.mp3", "title": "Stone Door", "author": "bonebrah", "license": "CC0 1.0", "url": "https://opengameart.org/content/stone-door"},
    {"file": "audio/bgm/lands.mp3", "title": "Fantasy Choir - 3 orchestral pieces", "author": "cesisco", "license": "CC0 1.0", "url": "https://opengameart.org/content/fantasy-choir-3-orchestral-pieces"},
    {"file": "audio/bgm/orario.mp3", "title": "A New Town (RPG Theme)", "author": "cynicmusic", "license": "CC0 1.0", "url": "https://opengameart.org/content/a-new-town-rpg-theme"},
    {"file": "audio/bgm/village.mp3", "title": "Town Theme RPG", "author": "cynicmusic", "license": "CC0 1.0", "url": "https://opengameart.org/content/town-theme-rpg"},
    {"file": "audio/amb/castle.mp3, audio/amb/lava.mp3, audio/amb/magic_hum.mp3, audio/amb/mall_indoor.mp3, audio/sfx/horn_2.mp3", "title": "Synthesised with ffmpeg (this project)", "author": "fantasy-atlas", "license": "CC0 1.0 (original)", "url": ""},
    {"file": "audio/sfx/crow_2.mp3", "title": "Crow", "author": "fvcalderan", "license": "CC0 1.0", "url": "https://opengameart.org/content/crow"},
    {"file": "audio/amb/city_ruin.mp3, audio/amb/lava.mp3, audio/amb/ship_ice.mp3, audio/sfx/engine_2.mp3", "title": "underwater or space engine rumble", "author": "gmason", "license": "CC0 1.0", "url": "https://opengameart.org/content/underwater-or-space-engine-rumble"},
    {"file": "audio/amb/city_ruin.mp3", "title": "Crows singing", "author": "IgnasD", "license": "CC0 1.0", "url": "https://opengameart.org/content/crows-singing"},
    {"file": "audio/amb/ship_ice.mp3, audio/sfx/glass_3.mp3", "title": "Ice breaking/shattering", "author": "IgnasD", "license": "CC0 1.0", "url": "https://opengameart.org/content/ice-breakingshattering"},
    {"file": "audio/amb/mountain_wind.mp3", "title": "Wind", "author": "IgnasD", "license": "CC0 1.0", "url": "https://opengameart.org/content/wind"},
    {"file": "audio/amb/field_birds.mp3", "title": "Ambient Bird Sounds", "author": "isaiah658", "license": "CC0 1.0", "url": "https://opengameart.org/content/ambient-bird-sounds"},
    {"file": "audio/amb/crypt.mp3", "title": "Loopable Dungeon Ambience", "author": "JaggedStone", "license": "CC0 1.0", "url": "https://opengameart.org/content/loopable-dungeon-ambience"},
    {"file": "audio/sfx/magic_3.mp3, audio/sfx/magic_4.mp3, audio/sfx/magic_5.mp3, audio/sfx/travel_2.mp3", "title": "Magic Spell SFX", "author": "JaggedStone", "license": "CC0 1.0", "url": "https://opengameart.org/content/magic-spell-sfx"},
    {"file": "audio/bgm/lands_boss.mp3", "title": "Epic Boss Battle (Boss Battle Music)", "author": "Juhani Junkala (SubspaceAudio)", "license": "CC0 1.0", "url": "https://opengameart.org/content/boss-battle-music"},
    {"file": "audio/bgm/tarkov.mp3", "title": "Post Apocalyptic Wastelands (Horror Atmosphere)", "author": "Juhani Junkala (SubspaceAudio)", "license": "CC0 1.0", "url": "https://opengameart.org/content/horror-atmosphere"},
    {"file": "audio/sfx/bell_1.mp3, audio/sfx/glass_1.mp3, audio/sfx/glass_2.mp3, audio/sfx/land_2.mp3, audio/sfx/land_3.mp3, audio/sfx/metal_hit_1.mp3, audio/sfx/metal_hit_2.mp3, audio/sfx/step_grass_1.mp3, audio/sfx/step_grass_2.mp3, audio/sfx/step_grass_3.mp3, audio/sfx/step_grass_4.mp3, audio/sfx/step_snow_1.mp3, audio/sfx/step_snow_2.mp3, audio/sfx/step_snow_3.mp3, audio/sfx/step_snow_4.mp3, audio/sfx/step_stone_1.mp3, audio/sfx/step_stone_2.mp3, audio/sfx/step_stone_3.mp3, audio/sfx/step_stone_4.mp3, audio/sfx/step_wood_1.mp3, audio/sfx/step_wood_2.mp3, audio/sfx/step_wood_3.mp3, audio/sfx/step_wood_4.mp3", "title": "Impact Sounds", "author": "Kenney", "license": "CC0 1.0", "url": "https://kenney.nl/assets/impact-sounds"},
    {"file": "audio/sfx/interact_1.mp3, audio/sfx/ui_click_1.mp3, audio/sfx/ui_open_1.mp3, audio/sfx/ui_open_2.mp3", "title": "Interface Sounds", "author": "Kenney", "license": "CC0 1.0", "url": "https://kenney.nl/assets/interface-sounds"},
    {"file": "audio/sfx/discover_1.mp3, audio/sfx/discover_2.mp3", "title": "Music Jingles", "author": "Kenney", "license": "CC0 1.0", "url": "https://kenney.nl/assets/music-jingles"},
    {"file": "audio/sfx/book_1.mp3, audio/sfx/book_2.mp3, audio/sfx/book_3.mp3, audio/sfx/coins_1.mp3, audio/sfx/coins_2.mp3, audio/sfx/creak_1.mp3, audio/sfx/creak_2.mp3, audio/sfx/door_wood_1.mp3, audio/sfx/door_wood_2.mp3, audio/sfx/door_wood_3.mp3, audio/sfx/interact_2.mp3, audio/sfx/jump_1.mp3, audio/sfx/jump_2.mp3, audio/sfx/lever_1.mp3", "title": "RPG Audio", "author": "Kenney", "license": "CC0 1.0", "url": "https://kenney.nl/assets/rpg-audio"},
    {"file": "audio/sfx/explosion_1.mp3, audio/sfx/thunder_2.mp3", "title": "Sci-fi Sounds", "author": "Kenney", "license": "CC0 1.0", "url": "https://kenney.nl/assets/sci-fi-sounds"},
    {"file": "audio/sfx/ui_click_2.mp3", "title": "UI Audio", "author": "Kenney", "license": "CC0 1.0", "url": "https://kenney.nl/assets/ui-audio"},
    {"file": "audio/amb/town.mp3", "title": "AMB Morning Sounds (Perfect Loop)", "author": "Kresiek The Furry", "license": "CC0 1.0", "url": "https://opengameart.org/content/amb-morning-sounds-perfect-loop"},
    {"file": "audio/amb/forest.mp3", "title": "AMB Outside 1", "author": "Kresiek The Furry", "license": "CC0 1.0", "url": "https://opengameart.org/content/amb-outside-1"},
    {"file": "audio/sfx/gunshot_distant_1.mp3, audio/sfx/gunshot_distant_2.mp3", "title": "Gunshots", "author": "kurt", "license": "CC0 1.0", "url": "https://opengameart.org/content/gunshots"},
    {"file": "audio/amb/swamp.mp3", "title": "Swamp Environment Audio", "author": "LokiF", "license": "CC0 1.0", "url": "https://opengameart.org/content/swamp-environment-audio"},
    {"file": "audio/sfx/engine_1.mp3", "title": "Car engine start 01", "author": "looneybits", "license": "CC0 1.0", "url": "https://opengameart.org/content/car-engine-start-01"},
    {"file": "audio/amb/castle.mp3, audio/amb/city_ruin.mp3, audio/amb/mountain_wind.mp3, audio/amb/ship_ice.mp3, audio/amb/snow_wind.mp3", "title": "wind1", "author": "Luke.RUSTLTD", "license": "CC0 1.0", "url": "https://opengameart.org/content/wind1"},
    {"file": "audio/sfx/travel_1.mp3", "title": "Teleport Spell", "author": "Ogrebane", "license": "CC0 1.0", "url": "https://opengameart.org/content/teleport-spell"},
    {"file": "audio/sfx/chest_1.mp3", "title": "open chest SFX", "author": "Oiboo", "license": "CC0 1.0", "url": "https://opengameart.org/content/open-chest-sfx"},
    {"file": "audio/amb/castle.mp3", "title": "Fireplace Sound loop", "author": "PagDev", "license": "CC0 1.0", "url": "https://opengameart.org/content/fireplace-sound-loop"},
    {"file": "audio/sfx/splash_3.mp3", "title": "Water Splash and sand footsteps", "author": "Peludo", "license": "CC0 1.0", "url": "https://opengameart.org/content/water-splash-and-sand-footsteps"},
    {"file": "audio/sfx/sparkle_3.mp3", "title": "Bell dings/chimes", "author": "PWL", "license": "CC0 1.0", "url": "https://opengameart.org/content/bell-dingschimes"},
    {"file": "audio/sfx/djump_2.mp3", "title": "Air whoosh", "author": "pyranostudios", "license": "CC0 1.0", "url": "https://opengameart.org/content/air-whoosh"},
    {"file": "audio/amb/cave.mp3", "title": "Dripping water loop", "author": "qubodup", "license": "CC0 1.0", "url": "https://opengameart.org/content/dripping-water-loop"},
    {"file": "audio/sfx/land_1.mp3", "title": "Jump Landing Sound", "author": "qubodup", "license": "CC0 1.0", "url": "https://opengameart.org/content/jump-landing-sound"},
    {"file": "audio/bgm/magic.mp3", "title": "Fantasy: Rising Moon", "author": "RandomMind", "license": "CC0 1.0", "url": "https://opengameart.org/content/fantasy-rising-moon"},
    {"file": "audio/bgm/kingdom.mp3", "title": "Medieval: Market Day", "author": "RandomMind", "license": "CC0 1.0", "url": "https://opengameart.org/content/medieval-market-day"},
    {"file": "audio/amb/harbor.mp3", "title": "Sea and river wave sounds", "author": "RandomMind", "license": "CC0 1.0", "url": "https://opengameart.org/content/sea-and-river-wave-sounds"},
    {"file": "audio/amb/harbor.mp3", "title": "Solo Seagull Sound Effects", "author": "Rango Mango", "license": "CC0 1.0", "url": "https://opengameart.org/content/solo-seagull-sound-effects"},
    {"file": "audio/sfx/bell_2.mp3, audio/sfx/bell_3.mp3, audio/sfx/chest_2.mp3, audio/sfx/explosion_3.mp3", "title": "100 CC0 SFX", "author": "rubberduck", "license": "CC0 1.0", "url": "https://opengameart.org/content/100-cc0-sfx"},
    {"file": "audio/amb/mall_indoor.mp3, audio/sfx/djump_1.mp3, audio/sfx/lever_2.mp3, audio/sfx/metal_hit_3.mp3, audio/sfx/thunder_1.mp3, audio/sfx/water_pour_2.mp3, audio/sfx/wind_gust_1.mp3", "title": "100 CC0 SFX #2", "author": "rubberduck", "license": "CC0 1.0", "url": "https://opengameart.org/content/100-cc0-sfx-2"},
    {"file": "audio/sfx/creak_3.mp3, audio/sfx/door_metal_1.mp3, audio/sfx/door_metal_2.mp3", "title": "100 CC0 metal and wood SFX", "author": "rubberduck", "license": "CC0 1.0", "url": "https://opengameart.org/content/100-cc0-metal-and-wood-sfx"},
    {"file": "audio/sfx/explosion_2.mp3, audio/sfx/gunshot_distant_3.mp3", "title": "25 CC0 bang / firework SFX", "author": "rubberduck", "license": "CC0 1.0", "url": "https://opengameart.org/content/25-cc0-bang-firework-sfx"},
    {"file": "audio/sfx/bubble_1.mp3, audio/sfx/bubble_2.mp3, audio/sfx/bubble_3.mp3, audio/sfx/splash_1.mp3, audio/sfx/splash_2.mp3, audio/sfx/swim_1.mp3, audio/sfx/swim_2.mp3, audio/sfx/swim_3.mp3, audio/sfx/water_pour_1.mp3", "title": "40 CC0 water / splash / slime SFX", "author": "rubberduck", "license": "CC0 1.0", "url": "https://opengameart.org/content/40-cc0-water-splash-slime-sfx"},
    {"file": "audio/sfx/coins_3.mp3, audio/sfx/door_stone_2.mp3, audio/sfx/fire_1.mp3, audio/sfx/fire_2.mp3, audio/sfx/gate_chain_2.mp3, audio/sfx/magic_1.mp3, audio/sfx/magic_2.mp3, audio/sfx/sparkle_1.mp3, audio/sfx/sparkle_2.mp3", "title": "80 CC0 RPG SFX", "author": "rubberduck", "license": "CC0 1.0", "url": "https://opengameart.org/content/80-cc0-rpg-sfx"},
    {"file": "audio/sfx/wind_gust_2.mp3", "title": "wind whoosh loop", "author": "SketchMan3", "license": "CC0 1.0", "url": "https://opengameart.org/content/wind-whoosh-loop"},
    {"file": "audio/amb/market.mp3, audio/amb/town.mp3", "title": "Crowd Shouting/Speaking Ambience", "author": "StarNinjas", "license": "CC0 1.0", "url": "https://opengameart.org/content/crowd-shoutingspeaking-ambience"},
    {"file": "audio/sfx/horn_1.mp3", "title": "Their Coming (generic horn sound)", "author": "StumpyStrust", "license": "CC0 1.0", "url": "https://opengameart.org/content/their-coming-generic-horn-sound"},
    {"file": "audio/sfx/anvil_2.mp3", "title": "Hammer on Anvil", "author": "themightyglider", "license": "CC0 1.0", "url": "https://opengameart.org/content/hammer-on-anvil"},
    {"file": "audio/amb/river.mp3", "title": "Park ambiences", "author": "Thimras", "license": "CC0 1.0", "url": "https://opengameart.org/content/park-ambiences"},
    {"file": "audio/sfx/step_grass_5.mp3", "title": "Different steps on wood, stone, leaves, gravel and mud", "author": "TinyWorlds", "license": "CC0 1.0", "url": "https://opengameart.org/content/different-steps-on-wood-stone-leaves-gravel-and-mud"},
    {"file": "audio/amb/lava.mp3", "title": "boiling water loops", "author": "TinyWorlds", "license": "CC0 1.0", "url": "https://opengameart.org/content/boiling-water-loops"},
    {"file": "audio/sfx/anvil_1.mp3", "title": "Blacksmith's Hammer", "author": "VishwaJai", "license": "CC0 1.0", "url": "https://opengameart.org/content/blacksmiths-hammer"},
    {"file": "audio/sfx/bird_flap_2.mp3", "title": "Dragon Flap", "author": "VishwaJai", "license": "CC0 1.0", "url": "https://opengameart.org/content/dragon-flap-0"},
    {"file": "audio/amb/night_insects.mp3", "title": "Crickets Ambient Noise - loopable", "author": "Wolfgang_", "license": "CC0 1.0", "url": "https://opengameart.org/content/crickets-ambient-noise-loopable"},
    {"file": "audio/amb/storm.mp3", "title": "Rain + Long Thunder", "author": "WuxiaScrub", "license": "CC0 1.0", "url": "https://opengameart.org/content/rain-long-thunder"},
    {"file": "audio/bgm/dungeon.mp3", "title": "Dungeon Ambience", "author": "yd", "license": "CC0 1.0", "url": "https://opengameart.org/content/dungeon-ambience"},
    {"file": "audio/bgm/tarkov_tension.mp3", "title": "Insistent: background loop", "author": "yd", "license": "CC0 1.0", "url": "https://opengameart.org/content/insistent-background-loop"},
    {"file": "audio/sfx/alarm_1.mp3", "title": "Short alarm", "author": "yd", "license": "CC0 1.0", "url": "https://opengameart.org/content/short-alarm"},
    {"file": "audio/sfx/crow_1.mp3", "title": "Crow caw", "author": "zeroisnotnull", "license": "CC0 1.0", "url": "https://opengameart.org/content/crow-caw"},
  ]
};
